
record _Unwind_Exception {
    exception_class: Int32;
    exception_cleanup: CodePointer[Int32, Pointer[_Unwind_Exception], Void];    
    private_1: Int32;
    private_2: Int32;
}

external _Unwind_RaiseException(p:Pointer[_Unwind_Exception]):Int32;

throw() {
    var exception = allocateMemory(_Unwind_Exception, 1);
    println("Throwing");
    _Unwind_RaiseException(exception); 
}

record Test {
    x: Int32;
}

overload Test() = Test(-1);

overload Test(x:Int32) : Test {
    println("Created ", x);
    returned.x = x;
}

overload Test(other:Test) : Test {
    println("Copied ", other.x);
    returned.x = other.x;
}

overload destroy(t:Test) {
    println("Destroyed ", t.x);
}

main () {
    try {
        var a = Test(1);
        throw();
        var b = Test(2);
    }
    catch {
        println("Caught!");
    }
}
